---
  - name: install meteor
    sudo: yes
    shell: curl https://install.meteor.com | /bin/sh

  - name: install meteor npm modules
    sudo: yes
    environment:
      PATH: $PATH:/usr/local/bin/
    npm: name={{ item }} global=yes state=present
    with_items:
      - meteorite
      - forever
